version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /release.*/


jobs:
  build:
    docker:
      - image: nixos/nix:2.3.6
    steps:
      - checkout
      - run:
          name: Add internal deps 
          command: |
            nix-env -iA nixpkgs.git
      - run: 
          name: Lint elm code
          command: nix-shell --run "elm-format --validate ." 
      - run: 
          name: Build
          command: nix-shell --run "make build" 
      - persist_to_workspace:
          root: ./public
          paths: 
            - index.html
            - elm.min.js
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ./public 
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@3.1.0
            git config user.email "ci@brestcomputer.club"
            git config user.name "ci"
      - add_ssh_keys:
          fingerprints:
            - "9c:c3:49:76:0a:02:af:9f:65:1b:d3:f8:10:08:4f:eb"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Publish" -d ./public
